// app/layout.tsx
import ClientProvider from "./ClientProvider";
import './globals.css';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en " >
      <body>
          <ClientProvider>
            {children}
          </ClientProvider>
      </body>
    </html>
  );
}
